konain/config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :pages, only: :show

  resources :projects do
    collection do
      get "fetch_project"
    end
    member do
      get 'fetch_sub_projects'
    end
  end

  ActiveAdmin.routes(self)
  resources :properties

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    member do
      get "assigned_properties"
      get "favourite_properties"
    end
  end

  resources :favourite_properties, only: [:create, :destroy]

  get '/agents', to: "users#agents"

  get '/lawyers', to: "users#lawyers"

  get '/architects', to: 'users#architects'

  post '/send_mail', to: 'emails#send_mail'

  get '/contact_us', to: 'emails#contact'

  post '/send_contact_mail', to: 'emails#send_contact_mail'

  get "/fetch_property_type", to: 'properties#fetch_property_type'

  get "/fetch_property_sub_type", to: 'properties#fetch_property_sub_type'

  get "/fetch_property_features", to: 'properties#fetch_property_features'

  get "/property_types", to: 'properties#property_types'

  get '/about_us', to: 'pages#about_us'

  get '/:permalink', to: "pages#show"

  get '/admin/fetch_types', to:"admin/properties#fetch_types"

  get '/admin/fetch_sub_types', to:"admin/properties#fetch_sub_types"

  get '/admin/fetch_features', to:"admin/properties#fetch_features"

  get '/admin/fetch_sub_projects/(:id)', to: 'admin/properties#fetch_sub_projects'

  root 'properties#home_page'

end

konain/app/models/user.rb
class User < ActiveRecord::Base

  paginates_per 10
  COUNTRIES = ["Pakistan"]
  CITIES = ['Lahore', 'Karachi', 'Islamabad']
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  ROLES = ['admin', 'agent', 'lawyer', 'architect']

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_one :attachment, as: :imageable, dependent: :destroy
  has_many :properties, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :favourite_properties, through: :favourites, source: :favourited, source_type: 'Property'
  has_many :emails, class_name: 'Email', foreign_key: :agent_id, dependent: :destroy
  has_many :agent_properties, class_name: 'Property', foreign_key: :agent_id, dependent: :destroy

  validates :name, presence: true, length: { in: 3..50 }

  validates :email, uniqueness:true, format: { with: EMAIL_REGEX,
              message: "format should be: user@example.com" }

  validates :home_phone_code, presence: true, format: { with: /\A(0\d{2,3})\z/,
              message: "can be 3 or 4 digits" }

  validates :home_phone_number, presence: true, format: { with: /\A(\d{8})\z/,
              message: "should have 8 digits" }

  validates :mobile_phone_code, presence: true, format: { with: /\A(03\d{2})\z/,
              message: "format should be: 03xx" }

  validates :mobile_phone_number, presence: true, format: { with: /\A(\d{7})\z/,
              message: "should have 7 digits" }

  validates :terms_and_conditions, acceptance: true
  validates :address, length: { maximum: 200 }, allow_blank: true

  validates :fax_code, allow_blank: true, format: { with: /\A(0\d{2,3})\z/,
              message: "can be 3 or 4 digits starting with digit 0" }

  validates :fax_number, allow_blank: true, format: { with: /\A(\d{7})\z/,
              message: "should have 7 digits" }

  validates :zip_code, allow_blank: true, numericality: true, length: { maximum: 50},
              format: { with: /\A(\d{4,9})\z/,
                       message: "can be minimum 4 and maximum 9 digits." }

  validates :agent_description, allow_blank: true, length: { maximum: 255 }

  accepts_nested_attributes_for :attachment, allow_destroy: true

  scope :agents, -> { where(role: 'agent') }
  scope :ordered_agents, -> { agents.order(id: :desc) }

  scope :non_agents, -> { where.not(role: 'agent') }
  scope :ordered_non_agents, -> { non_agents.order(id: :desc) }

  scope :subscribers, -> { where(subscriber: true) }
  scope :ordered_subscribers, -> { subscribers.order(id: :desc) }
  scope :subscribers_emails, -> { ordered_subscribers.pluck(:email) }

  scope :admins, -> { where(role: 'admin') }

  scope :lawyers, -> { where(role: 'lawyer') }
  scope :ordered_lawyers, -> { lawyers.order(id: :desc) }

  scope :architects, -> { where(role: 'architect') }
  scope :ordered_architects, -> { architects.order(id: :desc) }

  before_destroy :check_admin?

  def home_number
    [self.home_phone_code, self.home_phone_number].join("-")
  end

  def mobile_number
    [self.mobile_phone_code, self.mobile_phone_number].join("-")
  end

  def fax
    [self.fax_code, self.fax_number].join("-")
  end

  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = where(email: auth.info.email).first_or_create
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    end

    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        user.name = data["name"] if user.name.blank?
      end
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ['Subscribers']
      csv << ['emails']
      pluck(:email).each do |user|
        csv << [user]
      end
    end
  end

  def is_admin_or_agent?
    return true if self.admin?
    return true if self.agent?
    return false
  end

  def self.export_csv(properties, closed_properties, user)
    csv = CSV.generate( encoding: 'Windows-1251' ) do |csv|
      csv << ["Total Deals Closed"]
      csv << [closed_properties.length]
      csv << ["Sold/Rented Properties by Agent"]
      csv << ["Title", "Category", "Property SubType", "Property Type", "Sold/Rented at Price PKR.", "Location", "City", "Country"]
      closed_properties.each do |property|
        csv << [ property.title, property.category, property.property_sub_type, property.property_type, property.end_price, property.location, property.city, property.project.country ]
      end
      csv << ["Assigned Properties"]
      csv << ["Title", "Category", "Property SubType", "Property Type", "Price PKR.", "Location", "City", "Country"]
      properties.each do |property|
        csv << [ property.title, property.category, property.property_sub_type, property.property_type, property.price, property.location, property.city, property.project.country ]
      end
    end
  end

  def first_name
    name = self.name.split(" ")
    name[0]
  end

  def admin?
    role == 'admin'
  end

  def agent?
    role == 'agent'
  end

  def lawyer?
    role == 'lawyer'
  end


  private

  def check_admin?
    return false if self.admin?
  end

end

konain/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :assigned_properties, :favourite_properties]
  before_action :validate_user, only: [:edit, :update]
  before_action :set_featured_properties, only: [:agents, :show, :edit, :assigned_properties, :favourite_properties, :lawyers, :architects]
  before_action :authenticate_admin, only: [:destroy]
  before_action :set_params, only: [:show]
  before_action :pre_login_alerts, only: [:update]
  before_action :set_user_favourities, only: [:favourite_properties]
  before_action :set_favourited_params, only: [:show]
  before_action :build_email, only: [:agents, :lawyers, :architects]

  load_and_authorize_resource only: [:index, :new, :edit, :update, :create, :destroy, :agents, :lawyers, :architects]

  def index
    @users = User.subscribers

    respond_to do |format|
      format.html
      format.csv { render text: @users.to_csv }
    end
  end

  def show
    @user_properties = Property.perform_search(params)
    @array_of_property_fields = Property.property_fields_array(@user_properties)
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user, flash: { success: 'Your profile was successfully updated.' }
    else
      render '/devise/registrations/edit'
    end
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        format.html {
          flash[:success] = 'User was successfully destroyed'
          redirect_to referrer_path
        }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, flash: { error: 'User was not destroyed' } }
      end
    end
  end

  def agents
    @agents = User.includes(:attachment).ordered_agents.page(params[:page])
  end

  def lawyers
    @lawyers = User.includes(:attachment).ordered_lawyers.page(params[:page])
  end

  def architects
    @architects = User.includes(:attachment).ordered_architects.page(params[:page])
  end

  def assigned_properties
    params.merge!(agent_id: @user.id, state: Array(params[:state]))
    @user_properties = Property.perform_search(params)
    @array_of_property_fields = Property.property_fields_array(@user_properties)
    render 'show'
  end

  def favourite_properties
    params.merge!(state:  Array(params[:state]))
    @favourited = true
    @user_properties = Property.get_favourites(params)
    @array_of_property_fields = Property.property_fields_array(@user_properties)
    render 'show'
  end

  private

  def user_params
    params.require(:user).permit(:name, :home_phone_code, :home_phone_number,
                                 :mobile_phone_code, :mobile_phone_number, :terms_and_conditions,
                                 :uid, :provider, :oauth_token, :oauth_expires_at, :subscriber, :role,
                                 :agent_description, :fax_code, :fax_number, :city, :country, :address,
                                 :zip_code, :password, :password_confirmation,
                                  attachment_attributes: [:id, :image, :_destroy])
  end

  def set_user
    @user = User.find_by_id params[:id]
    return redirect_to :root, flash: { error: "User not found" } if @user.blank?
  end

  def validate_user
    return redirect_to :root, flash: { error: "You are not allowed to access this page" } unless @user == current_user
  end

  def authenticate_admin
    redirect_to :root, flash: { error: 'You are not authorized for this action' } unless current_user.admin?
  end

  def set_params
    state = params[:state].present? ? Array(params[:state]) : Property::REQUIRED_STATES
    if params[:favourited_type].present?
      params.merge!(favourited_user_id: @user.id, state: state)
    elsif params[:agent_id].present?
      params.merge!(agent_id: @user.id, state: state)
    else
      params.merge!(user_id: @user.id, state: state)
    end
  end

  def set_favourited_params
    if params[:favourited_type] == 'Property'
      @favourited = true
      set_user_favourities
    end
  end

  def build_email
    @email = Email.new
  end
end

konain/app/helpers/users_helper.rb
module UsersHelper

  def terms_and_conditions
    "I have read and accepted Konain Marketing Online #{link_to 'Terms and Conditions', '/terms_and_conditions', target: "blank" }".html_safe
  end

  def resource_name
    :user
  end

  def resource
    @resource || @user || User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def agent_image(agent)
    attachment = agent.attachment
    attachment.try(:image).try(:url, :featured) || 'no_agent_image_agent.jpg'
  end

  def user_image(user)
    attachment = user.attachment
    attachment.try(:image).try(:url, :featured) || 'no_agent_image_user.jpg'
  end

  def agents_image(agent)
    attachment = agent.attachment
    attachment.try(:image).try(:url, :featured) || 'no_agent_image_all_agents.jpg'
  end

  def can_edit?(user)
    user_signed_in? && user.id == current_user.id
  end

  def display_user_role(user)
    if user.lawyer?
      "Lawyer Info"
    elsif user.agent?
      "Agent Info"
    else
      "Seller Info"
    end
  end

  def included_in?(url)
    url.include?('/assigned_properties') || url.include?('/favourite_properties')
  end

  def add_data_to_params(id, state, category, favourited_type=nil, agent_id=nil)
    {
      id: id,
      state: state,
      category: category,
      favourited_type: favourited_type,
      agent_id: agent_id,
    }
  end

  def active_filter_tab(params, action)
    return "active" if params[:action] == action
  end

  def page_info(users, role)
    return ['No', role.pluralize.humanize, 'found'].join(' ') unless users.present?
    return ['Showing', users.length, [users.last.role, '(s)'].join].join(' ')
  end
end

konain/app/views/users/_agent_info.html.erb
<div id="contactAgent" class="modal hide fade sendMailAgentPopup" tabindex="-1" role="dialog" aria-labelledby="contactAgentLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times-circle" aria-hidden="true"></i></button>
    <h3>
      Send message to Agent <%= titleize(agent.name) %>
    </h3>
  </div>

  <div class="modal-body">
    <%= form_for @email, url: send_mail_path, method: :post do |f| %>
      <div class="controls controls-row form-horizontal">
        <div class="row-fluid control-group">
          <%= f.label :sender_name, 'Name:', class: 'span4' %>
          <%= f.text_field :sender_name, placeholder: 'Enter Your Name', required: true, class: 'span8' %>
        </div>
        <div class="row-fluid control-group">
          <%= f.label :contact, 'Contact Number:', class: 'span4' %>
          <%= f.text_field :contact, placeholder: '03001111111 / 04231111111', required: true, class: 'span8', pattern: "[0-9]{1,13}" %>
        </div>
        <div class="row-fluid control-group">
          <%= f.label :user_email, 'Your Email:', class: 'span4' %>
          <%= f.email_field :user_email, placeholder: 'user@example.com', class: 'span8' %>
          <%= hidden_field_tag :agent_id, agent.id %>
        </div>
      </div>

      <div class="controls row-fluid control-group">
        <%= f.label :body, 'Your Message:', class: 'span4' %>
        <div  class="span8">
        <%= f.text_area :body, placeholder: 'Write Your Message', required: true, rows: 12, class: '' %>
        </div>
      </div>

      <div class="controls">
        <%= f.submit 'Send Email', class: 'btn btn-contact submitBtn pull-right' %>
      </div>
    <% end %>
  </div>
</div>

<aside id="property_agent-2" class="widget property-agent">
  <h3 class="widget-title">
    Agent Info
  </h3>
  <div class="content-widget">

    <%= link_to image_tag(agent_image(agent)), assigned_properties_user_path(agent, state: "approved") %>
    <div class="agent-widget-name">
      <%= link_to titleize(agent.name), assigned_properties_user_path(agent, state: "approved") %>
    </div>

    <div class="agent-widget-phone">
      <i class="fa fa-mobile" aria-hidden="true"></i>
      <%= agent.mobile_number %>
    </div>

    <div class="agent-widget-phone">
      <i class="fa fa-phone" aria-hidden="true"></i>
      <%= agent.home_number %>
    </div>

    <div class="agent-widget-email">
      <i class="fa fa-envelope" aria-hidden="true"></i>
      <%= agent.email %>
    </div>

    <div class="clear"></div>
    <div class="agent-widget-excerpt">
      <%= truncate(agent.agent_description, omission: "", length: 255) %>
    </div>
    <div class="agent-desc">
      <a role="button" data-toggle="modal" class="button button-search-widget" href="#contactAgent">
        Contact Agent
      </a>
    </div>

  </div>
</aside>

konain/app/views/users/_email_form.html.erb
<div class='modal-body'>
  <%= form_for @email, url: send_mail_path, method: :post do |f| %>
    <div class='controls controls-row form-horizontal'>
      <div class='row-fluid control-group'>
        <%= f.label :sender_name, 'Name:', class: 'span4' %>
        <%= f.text_field :sender_name, placeholder: 'Enter Your Name', required: true, class: 'span8' %>
      </div>
      <div class='row-fluid control-group'>
        <%= f.label :contact, 'Contact Number:', class: 'span4' %>
        <%= f.text_field :contact, placeholder: '03001111111 / 04231111111', required: true, class: 'span8', pattern: '[0-9]{1,13}' %>
      </div>
      <div class='row-fluid control-group'>
        <%= f.label :user_email, 'Your Email:', class: 'span4' %>
        <%= f.email_field :user_email, placeholder: 'user@example.com', class: 'span8' %>
        <%= hidden_field_tag :agent_id, user.id %>
      </div>
    </div>

    <div class='controls row-fluid control-group'>
      <%= f.label :body, 'Your Message:', class: 'span4' %>
      <div  class='span8'>
        <%= f.text_area :body, placeholder: 'Write Your Message', required: true, rows: 12, class: '' %>
      </div>
    </div>

    <div class='controls'>
      <%= f.submit 'Send Email', class: 'btn btn-contact submitBtn pull-right' %>
    </div>
  <% end %>
</div>

konain/app/views/users/_show.html.erb
<%= render "show_filters", params: params %>

<% if user_properties.present? %>
  <% user_properties.each do |property| %>

    <div class="row-fluid">
      <div class="row-fluid property-listing <%= catergory_class(property) %> clearfix property-listing-col-margins all-property-list">
        <div class="listing-image span5">
          <div class="property-image-container">
            <%= link_to image_tag(property.cover_image), property %>
          </div>
          <div class="listing-meta">
            <ul>
              <li>
                <i class="ico-size"></i>
                <%= property.land_area %>
                <%= area_units_abbreviation(property.area_unit) %>
              </li>
              <li>
                <i class="ico-bedroom"></i>
                <%= property.bedroom_count %>
              </li>
              <li>
                <i class="ico-bathroom"></i>
                <%= property.bathroom_count %>
              </li>
            </ul>
          </div>
        </div>

        <div class="listing-info span7 usersList">
          <div class="listing-title">
            <h3><%= link_to property.title_slug, property %></h3>
          </div>
          <div class="listing-content">
            <div class="listing-property-price">
              <span class="price-curr">PKR. <%= render_price(property.price) %> </span>
              <span class="price-postfix"></span>
            </div>
            <div class="listing-excerpt">
              <p><%= property.description %></p>
            </div>
          </div>

          <div class="listing-address">
            <i class="fa fa-map-marker" aria-hidden="true"></i>
            <%= project(property).location %>, <%= property.city %>
            <a href="#" data-toggle="modal" data-target="#myMapModal-<%= property.id %>" class="map-link">View Map</a>
            <div class="modal fade hide" id="myMapModal-<%= property.id %>">
              <div class="modal-dialog">
                <div class="modal-content sendMailAgentPopup">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                      <i class="fa fa-times-circle" aria-hidden="true"></i>
                    </button>
                    <h3 class="modal-title"><%= property_address(property) %></h3>
                  </div>
                  <div class="modal-body">
                    <div class="row map-row">
                      <div id="map-canvas-<%= property.id %>" class="map-canvas"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <% if user_signed_in? && is_owner?(property) %>
            <div class="edit-delete-btns">
              <%= link_to edit_property_path(property) do %>
                <i class="fa fa-pencil" aria-hidden="true"></i>
              <% end %> |
              <%= link_to property, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fa fa-trash-o" aria-hidden="true"></i>
              <% end %>
            </div>
          <% end %>
          <% if @favourited.present? %>
            <div id='favourited_<%= property.id %>' class='favourite-feature'>
              <%= render 'favourite_properties/favourited', property: property, user_favourited_active: true, active_category: active_category %>
             </div>
          <% end %>
        </div>

        <div class="property-status <%= catergory_text_class(property) %>">
          <%= category(property) %>
        </div>
      </div>
    </div>
  <% end %>

<% else %>

  <div class="row-fluid">
    <h2>No Properties found</h2>
  </div>
<% end %>

<div class="property-pagination">
  <ul>
    <li><%= paginate user_properties, remote: true %></li>
  </ul>
</div>

konain/app/views/users/_show_filters.html.erb
<div id="title-listing" class="container home-feature-listing-links">
  <h2 class="property-list-title">
    <%= titleize(@user.first_name) %>'s Properties
  </h2>
  <div class="property-list-by sort-title">
    <% if can_edit?(@user) %>
      <%= link_to "Uploaded", user_path(add_data_to_params(@user.id, nil, params[:category])), remote: true, id: "uploaded", class: active_filter_tab(params, "show") %>
      <%= link_to "Approved", user_path(add_data_to_params(@user.id, "approved", params[:category])), remote: true, id: "approved" %>
      <%= link_to "Pending", user_path(add_data_to_params(@user.id, "pending", params[:category])), remote: true, id: "pending" %>
      <%= link_to "Favourited", favourite_properties_user_path(add_data_to_params(@user.id, "approved", params[:category], "Property")), remote: true, id: "favourited" %>
    <% end %>

    <% if @user.agent? %>
      <%= link_to "Assigned", assigned_properties_user_path(add_data_to_params(@user.id, "approved", params[:category], nil, @user.id)), remote: true, id: "assigned", class: active_filter_tab(params, "assigned_properties") %>
    <% end %>
  </div>
</div>

<div class="property-sort">
  <div class="sort-title">
    <span class="sort-by sort-by-text-color">Show: </span>
    <%= link_to "All", user_path(add_data_to_params(@user.id, params[:state], nil, params[:favourited_type], params[:agent_id])), class: "active", id: "all", remote: true %>
    <%= link_to "For Rent", user_path(add_data_to_params(@user.id, params[:state], 'Rent', params[:favourited_type], params[:agent_id])), id: "rent", remote: true %>
    <%= link_to "On Sale", user_path(add_data_to_params(@user.id, params[:state], 'Sale', params[:favourited_type], params[:agent_id])), id: "sale", remote: true %>
  </div>
</div>

konain/app/views/users/_user_info.html.erb
<div class="row-fluid sellerInfo">
  <h3  class="f30"><%= display_user_role(user) %></h3>
  <div class="row-fluid user-listing clearfix userProfileImgSec">
    <div class="agent-image span4">
      <div class="agent-image-container">
        <%= image_tag user_image(user), class: "agent-image-size" %>
      </div>
    </div>
    <div class="listing-info span8">
      <div class="listing-title">
        <h1><%= user.name %>
          <% if user.city.present? %>
            - <%= user.city %>
          <% end %>
        </h1>
        <% if can_edit?(@user) %>
          <div class="edit-delete-btns">
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-pencil" aria-hidden="true"></i>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="listing-content">
        <% if user.address.present? %>
          <div class="listing-excerpt">
            <div class="row-fluid emailFaxSec">
              <div class="textWrappSec">
                <label>Address: </label>
                <span>
                  <%= user.address.titleize %>
                  <% if user.city.present? %>
                    , <%= user.city %>
                  <% end %>
                </span>
              </div>
            </div>
          </div>
        <% end %>

        <div class="listing-excerpt">
          <div class="row-fluid emailFaxSec">
            <div class="pull-left">
              <label>Email:</label>
              <span class="emailTxt"><%= user.email %></span>
            </div>
            <% if user.fax_code.present? && user.fax_number.present? %>
              <div class="pull-left">
                <label>Fax: </label>
                <span><%= user.fax %></span>
              </div>
            <% end %>
            <div class="clearfix"></div>
            <% if user.agent_description.present? %>
              <div class="textWrappSec">
                <label>Bio: </label>
                <span class="bio"><%= user.agent_description %></span>
              </div>
            <% end %>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>

      <div class="listing-address">
        <table>
          <td class="agent-phone-info">
            <i class="fa fa-mobile" aria-hidden="true"></i>
            <span><%= user.home_number %></span>
          </td>
          <td class="agent-phone-info">
            <i class="fa fa-phone" aria-hidden="true"></i>
              <%= user.mobile_number %>
          </td>
        </table>
      </div>
    </div>
  </div>
</div>

konain/app/views/users/agents.html.erb
<%= render "shared/banner", banner_heading: "Agents Listing", banner_name: "Agent Listings", heading_tag: :h1 %>

<div class="container">

  <div id="main" class="row-fluid agentsListingPage">
    <section  id="content" class="span9" role="main">

      <div class="agent-sort">
        <span class="paginate-info"><%= page_entries_info @agents %></span>
        <div class="paginationBtns">
          <%= link_to_previous_page @agents, '<i class="fa fa-chevron-left"></i>Back'.html_safe, class: "paginate-button back-button" %>
          <%= link_to_next_page @agents, 'Next<i class="fa fa-chevron-right"></i>'.html_safe, class: "paginate-button next-button" %>
        </div>
        <div class="clearfix"></div>
      </div>

      <% if @agents.present? %>
        <% @agents.each do |agent| %>

          <div class="row-fluid">
            <div class="row-fluid agent-listing clearfix">
              <div class="agent-image-listing span4">
                <div class="agent-image-container">
                  <%= link_to image_tag(agents_image(agent), class: "agent-image-size"), assigned_properties_user_path(agent, state: "approved") %>
                </div>
              </div>
              <div class="listing-info span8">
                <div class="listing-title">
                  <h2><%= link_to titleize(agent.name), assigned_properties_user_path(agent, state: "approved") %>
                    <% if agent.city.present? %>
                      - <%= agent.city %>
                    <% end %>
                  </h2>
                </div>
                <div class="listing-content">
                  <div class="listing-excerpt">
                    <p><%= agent.agent_description %></p>
                  </div>
                </div>

                <div class="listing-address">
                  <table>
                    <td class="agent-phone-info">
                      <i class="fa fa-mobile" aria-hidden="true"></i>
                      <%= agent.home_number %>
                    </td>
                    <td class="agent-phone-info">
                      <i class="fa fa-phone" aria-hidden="true"></i>
                      <%= agent.mobile_number %>
                    </td>
                    <td class="agent-phone-info">
                      <i class="fa fa-envelope" aria-hidden="true"></i>
                      <a data-toggle="modal" href="#contact_<%= agent.id %>">Send Email</a>
                    </td>

                    <div id="contact_<%= agent.id %>" class="modal hide fade sendMailAgentPopup" tabindex="-1" role="dialog" aria-labelledby="contactAgentLabel" aria-hidden="true">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times-circle" aria-hidden="true"></i></button>
                        <h3>
                          Send message to Agent <%= agent.name %>
                        </h3>
                      </div>

                      <div class="modal-body">
                        <%= form_for @email, url: send_mail_path, method: :post do |f| %>
                          <div class="controls controls-row form-horizontal">
                            <div class="row-fluid control-group">
                              <%= f.label :sender_name, 'Name:', class: 'span4' %>
                              <%= f.text_field :sender_name, placeholder: 'Enter Your Name', required: true, class: 'span8' %>
                            </div>
                            <div class="row-fluid control-group">
                              <%= f.label :contact, 'Contact Number:', class: 'span4' %>
                              <%= f.text_field :contact, placeholder: '03001111111 / 04231111111', required: true, class: 'span8', pattern: "[0-9]{1,13}" %>
                            </div>
                            <div class="row-fluid control-group">
                              <%= f.label :user_email, 'Your Email:', class: 'span4' %>
                              <%= f.email_field :user_email, placeholder: 'user@example.com', class: 'span8' %>
                              <%= hidden_field_tag :agent_id, agent.id %>
                            </div>
                          </div>

                          <div class="controls row-fluid control-group">
                            <%= f.label :body, 'Your Message:', class: 'span4' %>
                            <div  class="span8">
                            <%= f.text_area :body, placeholder: 'Write Your Message', required: true, rows: 12, class: '' %>
                            </div>
                          </div>

                          <div class="controls">
                            <%= f.submit 'Send Email', class: 'btn btn-contact submitBtn pull-right' %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </table>
                </div>
              </div>
            </div>
          </div>
        <% end %>

      <% else %>

        <div class="row-fluid">
          <h2>No Agents found</h2>
        </div>
      <% end %>

      <div class="property-pagination">
        <ul>
          <li><%= paginate @agents %></li>
        </ul>
      </div>
    </section>

    <section id="sidebar" class="span3" role="complementary">
      <%= render 'properties/search_form' %>
      <% if @properties.present? %>
        <%= render 'properties/featured_properties', properties: @properties %>
      <% end %>
    </section>
  </div>
</div>