konain/config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :pages, only: :show

  resources :projects do
    collection do
      get "fetch_project"
    end
    member do
      get 'fetch_sub_projects'
    end
  end

  ActiveAdmin.routes(self)
  resources :properties

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    member do
      get "assigned_properties"
      get "favourite_properties"
    end
  end

  resources :favourite_properties, only: [:create, :destroy]

  get '/agents', to: "users#agents"

  get '/lawyers', to: "users#lawyers"

  get '/architects', to: 'users#architects'

  post '/send_mail', to: 'emails#send_mail'

  get '/contact_us', to: 'emails#contact'

  post '/send_contact_mail', to: 'emails#send_contact_mail'

  get "/fetch_property_type", to: 'properties#fetch_property_type'

  get "/fetch_property_sub_type", to: 'properties#fetch_property_sub_type'

  get "/fetch_property_features", to: 'properties#fetch_property_features'

  get "/property_types", to: 'properties#property_types'

  get '/about_us', to: 'pages#about_us'

  get '/:permalink', to: "pages#show"

  get '/admin/fetch_types', to:"admin/properties#fetch_types"

  get '/admin/fetch_sub_types', to:"admin/properties#fetch_sub_types"

  get '/admin/fetch_features', to:"admin/properties#fetch_features"

  get '/admin/fetch_sub_projects/(:id)', to: 'admin/properties#fetch_sub_projects'

  root 'properties#home_page'

end

konain/app/models/project.rb
class Project < ActiveRecord::Base

  include MathCalculations

  PAGINATION = 10
  CITIES = ['Lahore', 'Karachi', 'Islamabad', 'Gwadar']
  COUNTRIES = ['Pakistan']
  DEFAULT_PROJECTS_TITLE = ['Other - Lahore', 'Other - Islamabad', 'Other - Karachi']

  has_many :properties, dependent: :destroy
  has_many :attachments, as: :imageable, dependent: :destroy
  has_many :sub_projects, dependent: :destroy

  validates :title, :location, :city, :country, presence: true
  validates :title, length: { maximum: 30 }
  validates :description, length: { maximum: 2000 }
  validates :location, length: { maximum: 60 }

  accepts_nested_attributes_for :attachments, allow_destroy: true

  geocoded_by :full_address
  after_validation :geocode

  scope :ordered, -> { order(id: :desc) }
  scope :projects_by_city, -> (city){ where(city: city) }

  after_save :adjust_properties_city
  after_save :adjust_sub_projects_city

  def self.default_scope
    where(project_id: nil)
  end

  def full_address
    [location, city, country].join(", ")
  end

  def self.project_fields_array(projects)
    projects.collect{ |project| [project.latitude, project.longitude, project.id] }
  end

  def self.perform_search(params)
    search_params = default_search_params

    search_params[:page] = params[:page]
    search_params[:per_page] = PAGINATION
    search_params[:with][:city] = Zlib::crc32(params[:city]) if params[:city].present?
    search_params[:without][:title_filter] = DEFAULT_PROJECTS_TITLE.collect{ |title| Zlib::crc32(title) } if params[:title].blank?
    search_params[:conditions][:title] = params[:title] if params[:title].present?

    self.search search_params
  end

  def self.default_search_params
    {
      conditions: {},
      with: { project_id: 0 },
      without: {},
      sql: { include: :attachments },
      order: "id DESC",
    }
  end

  def lat_to_rad
    Project.to_radians(self.latitude)
  end

  def lng_to_rad
    Project.to_radians(self.longitude)
  end

  def cover_image
    attachments = self.attachments
    picture = attachments.first
    picture.try(:image).try(:url, :index) || 'no_image_index.png'
  end

  private

  def adjust_properties_city
    properties.each do |property|
      property.city = self.city
      property.latitude = self.latitude
      property.longitude = self.longitude
      property.save
    end
  end

  def adjust_sub_projects_city
    sub_projects.update_all(city: self.city)
  end

end

konain/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_admin_user!, only: [:edit, :new, :create, :update, :destroy]
  before_action :set_project, only: [:show, :edit, :update, :destroy, :fetch_sub_projects]
  before_action :set_featured_properties, only: [:index]

  load_and_authorize_resource only: [:index, :show, :new, :edit, :update, :create, :destroy]

  def index
    @projects = Project.perform_search(params)
    gon.array_of_projects_fields = Project.project_fields_array(@projects)
  end

  def show
    gon.project_location = {"lat" => @project.latitude, "lng" => @project.longitude}
    @attachments = @project.attachments
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, flash: { success: 'Project was successfully added.' } }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, flash: { success: 'Project was successfully updated' } }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, flash: { error: 'Project was not updated.' } }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @project.destroy
        format.html { redirect_to projects_path, flash: { success: 'Project was successfully destroyed' } }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, flash: { error: 'Project was not destroyed' } }
      end
    end
  end

  def fetch_project
    @fetch_type = params[:fetch_type]
    @projects = Project.projects_by_city(params[:city]).collect{ |project| [project.title, project.id] }
    @sub_projects = SubProject.projects_by_city(params[:city]).collect{ |project| [project.title, project.id] }
  end

  def fetch_sub_projects
    @fetch_type = params[:fetch_type] if params[:fetch_type].present?
    @project = Project.find_by_id(params[:id])
    @sub_projects = @project.sub_projects.ordered.pluck(:title, :id) if @project.sub_projects.exists?
    respond_to do |format|
      format.js { render 'fetch_sub_projects' }
    end
  end

  private

    def set_project
      @project = Project.find_by_id(params[:id])
      return redirect_to :root, flash: { error: "Project was not found." } if @project.blank?
    end

    def project_params
      params.require(:project).permit(:title, :description, :location, :city,
                    :country, :latitude, :longitude, attachments_attributes: [:id, :image, :_destroy])
    end
end

konain/app/helpers/projects_helper.rb
module ProjectsHelper

  def project_title(project)
    [project.title.titleize, project.location.titleize, project.city].join(", ")
  end

  def project_address(project)
    [project.location.titleize, project.city, project.country].join(", ")
  end

end

konain/app/views/projects/_form.html.erb
<div class="container">
  <div class="row-fluid">
    <section class="span9">
      <%= nested_form_for(@project, html: { multipart: true }) do |f| %>
        <% if @project.errors.any? %>

          <div class="alert alert-error alert-block">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <ul>
              <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>

        <% end %>
        <div class="box-section form-horizontal">
          <h1 class="title-section">Project Location</h1>
          <div class="box-content">
            <p class="red-clr">*Required fields</p>

            <div class="row-fluid control-group">
              <div class="span3">
                <%= f.label :country, 'Country:*', class: 'form-label-align' %>
              </div>
              <div class="span9">
                <div class="row-fluid">
                  <div class="span9">
                    <span class="selectwrap">
                      <%= f.select :country, Project::COUNTRIES, { include_blank: 'Select Country' }, required: true %>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row-fluid control-group">
              <div class="span3">
                <%= f.label :city, 'City:*', class: 'form-label-align' %>
              </div>
              <div class="span9">
                <div class="row-fluid">
                  <div class="span9">
                    <span class="selectwrap">
                      <%= f.select :city, Project::CITIES, { include_blank: 'Select City' }, required: true %>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row-fluid control-group">
              <div class="span3">
                <%= f.label :location, 'Location:*', class: 'form-label-align' %>
              </div>
              <div class="span9">
                <div class="row-fluid">
                  <div class="span9">
                    <%= f.text_field :location, required: true, maxlength: 60, placeholder: 'Enter Location' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="box-section form-horizontal">
          <h1 class="title-section">Project Detail</h1>
          <div class="box-content">
            <div class="row-fluid control-group">
              <div class="span3">
                <%= f.label :title, 'Title:*', class: 'form-label-align' %>
              </div>
              <div class="span9">
                <div class="row-fluid">
                  <div class="span9">
                    <%= f.text_field :title, required: true, maxlength: 30, placeholder: 'Enter Title' %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row-fluid control-group">
              <div class="span3">
                <%= f.label :description, 'Description:', class: 'form-label-align' %>
              </div>
              <div class="span9">
                <div class="row-fluid">
                  <div class="span9">
                    <%= f.text_area :description, maxlength: 500, placeholder: 'Enter Description' %>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
        <div class="box-section">
          <h1 class="title-section">Add Images</h1>
          <div class="box-content">
            <div class='field'>
              <%= f.fields_for :attachments do |attachment| %>
                <%= attachment.file_field :image %>
                <%= image_tag attachment.object.image.url(:thumb) if attachment.object.image.present? %>
                <%= attachment.link_to_remove 'Remove' %>
              <% end %>
            </div>

            <div class="add-image-btn">
              <%= f.link_to_add :attachments, class: 'btnPrimary' do %>
                <i class="fa fa-plus-circle" aria-hidden="true"></i>  Add an Image
              <% end %>
            </div>
          </div>
        </div>

        <div class='actions'>
          <%= link_to 'Back', projects_path, class:'pull-left btnPrimary' %>
          <%= f.submit 'Upload', class: 'btnPrimary pull-right' %>
          <div class="clearall"></div>
        </div>
      <% end %>
    </section>
    <section id="sidebar" class="span3" role="complementary">
      <%= render 'properties/search_form' %>
    </section>
  </div>
</div>

konain/app/views/projects/edit.html.erb
<%= render "shared/banner", banner_heading: "Edit Project", heading_tag: :h2 %>

<%= render 'form' %>

konain/app/views/projects/fetch_project.js.erb
<% if @fetch_type == 'side_bar' %>
  $('#side_bar_prop_id').html('<%= raw j options_for_select(["Society"]) %>');
  $('#side_bar_prop_phase_id').html('<%= raw j options_for_select(["Phase"]) %>');

  <% if @projects.present? %>
    $("#side_bar_prop_id").append("<%= raw j options_for_select(@projects) %>");
  <% else %>
    $("#side_bar_prop_id").append("<%= raw j options_for_select(projects_list) %>");
  <% end %>

  <% if @sub_projects.present? %>
    $('#side_bar_prop_phase_id').append('<%= raw j options_for_select(@sub_projects) %>');
  <% end %>
<% else %>
  $('#property_project_id').html('<%= raw j options_for_select(["Society"]) %>');
  $('#property_sub_project_id').html('<%= raw j options_for_select(["Phase"]) %>');

  <% if @projects.present? %>
    $("#property_project_id").append("<%= raw j options_for_select(@projects) %>");
  <% else %>
    $("#property_project_id").append("<%= raw j options_for_select(projects_list) %>");
  <% end %>

  <% if @sub_projects.present? %>
    $('#property_sub_project_id').append('<%= raw j options_for_select(@sub_projects) %>');
  <% end %>
<% end %>

konain/app/views/projects/fetch_sub_projects.js.erb
<% if @fetch_type.present? && @fetch_type == 'side_bar' %>
  <% if @sub_projects.present? %>
    $('#side_bar_prop_phase_id').html('<%= raw j options_for_select(["Phase"]) %>');
    $('#side_bar_prop_phase_id').append('<%= j options_for_select(@sub_projects) %>');
  <% else %>
    $('#side_bar_prop_phase_id').html('<option>No Phase</option>');
  <% end %>
<% else %>
  <% if @sub_projects.present? %>
    $('#property_sub_project_id').html('<%= raw j options_for_select(["Phase"]) %>');
    $('#property_sub_project_id').append('<%= j options_for_select(@sub_projects) %>');
  <% else %>
    $('#property_sub_project_id').html('<option>No Phase</option>');
  <% end %>
<% end %>

konain/app/views/projects/index.html.erb
<%= render "shared/banner", banner_heading: "Projects Listing", banner_name: "Projects Listings", heading_tag: :h1 %>

<div class="container">

  <div id="main" class="row-fluid">
    <section  id="content" class="span9" role="main">

      <% if @projects.present? %>

        <div class="agent-sort">
          <span class="paginate-info">
            <%= "#{@projects.length} project(s)" %> <%= "in #{params[:city]}" if params[:city].present? %>
          </span>
          <div class="paginationBtns">
            <%= link_to_previous_page @projects, '<i class="fa fa-chevron-left"></i>Back'.html_safe, class: "paginate-button back-button" %>
            <%= link_to_next_page @projects, 'Next<i class="fa fa-chevron-right"></i>'.html_safe, class: "paginate-button next-button" %>
          </div>
          <div class="clearfix"></div>
        </div>

        <% @projects.each do |project| %>

          <div class="row-fluid">
            <div class="row-fluid property-listing <%= pre_login_listing %> clearfix property-listing-col-margins all-property-list project-list-section">
              <div class="listing-image span5">
                <div class="property-image-container">
                  <%= link_to image_tag(project.cover_image), project %>
                </div>
              </div>

              <div class="listing-info span7">
                <div class="listing-title">
                  <h2><%= link_to project.title.titleize, project %></h2>
                </div>
                <div class="project-description">
                  <%= truncate(project.description, omission: "... (continued)", length: 300) %>
                </div>

                <div class="listing-address">
                  <span class="location-text"><i class="fa fa-map-marker" aria-hidden="true"></i>
                  <%= project.location.titleize %>, <%= project.city %></span>
                  <a href="#" data-toggle="modal" data-target="#myMapModal-<%= project.id %>" class="map-link">View Map</a>
                  <div class="modal fade hide" id="myMapModal-<%= project.id %>">
                    <div class="modal-dialog">
                      <div class="modal-content sendMailAgentPopup">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal"><i class="fa fa-times-circle" aria-hidden="true"></i></button>
                          <h3 class="modal-title"><%= project.full_address.titleize %></h3>
                        </div>
                        <div class="modal-body">
                          <div class="row map-row">
                            <div id="project-map-canvas-<%= project.id %>" class="map-canvas"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <span class="seperator"></span>
                  <span class="pro-link">
                    <%= link_to "View All Properties", properties_path(project_id: project.id) %>
                  </span>
                </div>
<!--
                <div class="edit-delete-btns">
                  <%# if user_signed_in? && current_user.admin? %>
                    <%#= link_to edit_project_path(project) do %>
                      <i class="fa fa-pencil" aria-hidden="true"></i>
                    <%# end %> |
                    <%#= link_to project, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="fa fa-trash-o" aria-hidden="true"></i>
                    <%# end %>
                  <%# end %>
                </div> -->
              </div>

            </div>
          </div>
        <% end %>

      <% else %>

        <div class="row-fluid">
          <h2>No projects found</h2>
        </div>
      <% end %>

      <div class="property-pagination">
        <ul>
          <li><%= paginate @projects %></li>
        </ul>
      </div>
    </section>
    <section id="sidebar" class="span3" role="complementary">
      <%= render 'properties/search_form' %>
    </section>
    <% if @properties.present? %>
      <section id="sidebar" class="span3 pull-right" role="complementary">
        <%= render 'properties/featured_properties', properties: @properties %>
      </section>
    <% end %>
  </div>

</div>
<% if @projects.present? %>
  <% content_for :map_initializer do %>
    <script type='text/javascript' src='http://maps.google.com/maps/api/js?sensor=false'></script>
  <% end %>
  <% content_for :js_init do %>
    ProjectModalMap.init();
  <% end %>
<% end %>

konain/app/views/projects/new.html.erb
<%= render "shared/banner", banner_heading: "Upload Project", heading_tag: :h2 %>

<%= render 'form' %>

konain/app/views/projects/show.html.erb
<%= render "shared/banner", banner_heading: "Project Details", banner_name: "Project Details", heading_tag: :h2 %>

<div class="clearfix"></div>
<div class="content-wrapper">
  <div class="container">

    <div id="main" class="row-fluid">
      <section  id="content" class="span9" role="main">
        <div class="clearfix"></div>
        <article class="type-property">

          <% if @attachments.present? %>
            <%= render 'shared/attachments_carousel', attachments: @attachments %>
          <% end %>

          <div class="single-property-content-wrapper">

            <header class="single-property-header">
              <h3 class="single-property-title">
                <%= project_title(@project) %>
              </h3>
              <p class="single-property-address">
                <%= project_address(@project) %>
              </p>
            </header>

            <div class="project-description">
              <%= @project.description %>
              <p>&nbsp;</p>
            </div>

            <div class="single-property-map">
              <div id="the_map" class="map-wrap clearfix">
                <span class="map-label">Project Map</span>
                <div id="project-map"></div>
              </div>
            </div>
          </div>
        </article>
        <div class="btn-section">
          <%= link_to 'Back', projects_path %>
          <%= link_to 'View All Properties', properties_path(project_id: @project.id) %>
          <%# if user_signed_in? && current_user.admin? %>
            <%#= link_to 'Edit', edit_project_path(@project) %>
            <%#= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%# end %>
        </div>
      </section>
      <section id="sidebar" class="span3" role="complementary">
        <%= render 'properties/search_form' %>
      </section>
    </div>
  </div>
</div>
<% content_for :map_initializer do %>
  <script type='text/javascript' src='http://maps.google.com/maps/api/js?sensor=false'></script>
<% end %>
<% content_for :js_init do %>
  ProjectMap.init();
<% end %>