konain/config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :pages, only: :show

  resources :projects do
    collection do
      get "fetch_project"
    end
    member do
      get 'fetch_sub_projects'
    end
  end

  ActiveAdmin.routes(self)
  resources :properties

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    member do
      get "assigned_properties"
      get "favourite_properties"
    end
  end

  resources :favourite_properties, only: [:create, :destroy]

  get '/agents', to: "users#agents"

  get '/lawyers', to: "users#lawyers"

  get '/architects', to: 'users#architects'

  post '/send_mail', to: 'emails#send_mail'

  get '/contact_us', to: 'emails#contact'

  post '/send_contact_mail', to: 'emails#send_contact_mail'

  get "/fetch_property_type", to: 'properties#fetch_property_type'

  get "/fetch_property_sub_type", to: 'properties#fetch_property_sub_type'

  get "/fetch_property_features", to: 'properties#fetch_property_features'

  get "/property_types", to: 'properties#property_types'

  get '/about_us', to: 'pages#about_us'

  get '/:permalink', to: "pages#show"

  get '/admin/fetch_types', to:"admin/properties#fetch_types"

  get '/admin/fetch_sub_types', to:"admin/properties#fetch_sub_types"

  get '/admin/fetch_features', to:"admin/properties#fetch_features"

  get '/admin/fetch_sub_projects/(:id)', to: 'admin/properties#fetch_sub_projects'

  root 'properties#home_page'

end

konain/app/controllers/favourite_properties_controller.rb
class FavouritePropertiesController < ApplicationController

  before_action :set_property

  def create
    @favourited = Favourite.create(favourited: @property, user: current_user)
    set_user_favourities
  end

  def destroy
    @user_favourited = params[:user_favourited_active]
    @category = params[:category]
    @unfavourited = Favourite.where(favourited_id: @property.id, user_id: current_user.id).first
    @unfavourited.destroy if @unfavourited.present?
    set_user_favourities
  end

  private

    def set_property
      @property = Property.find(params[:id])
      return redirect_to :root, flash: { error: "Property was not found" } if @property.blank?
    end

end

konain/app/views/favourite_properties/_favourited.html.erb
<% if user_signed_in? && @favourities.include?(property.id) %>
  <%= link_to favourite_property_path(property, user_favourited_active: user_favourited_active, category: local_assigns[:active_category].present? ? active_category : '' ), method: :delete, remote: true do %>
    <i class="fa fa-heart active" aria-hidden="true"></i>
  <% end %>
<% elsif user_signed_in? %>
  <%= link_to favourite_properties_path(id: property.id), method: :post, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true"></i>
  <% end %>
<% end %>

konain/app/views/favourite_properties/create.js.erb
<% if @favourited.valid? %>
  $("#favourited_<%= @property.id %>").html("<%= escape_javascript(render 'favourited', property: @property, user_favourited_active: false) %>");
<% else %>
  $('.errors').html('<h4>Error</h4>')
<% end %>

konain/app/views/favourite_properties/destroy.js.erb
<% if @user_favourited == 'true' %>
  $('#favourited_<%= @property.id %>').parents(':eq(1)').fadeOut(function() { $(this).remove(); });
  url = '/users/<%= current_user.id %>/favourite_properties?favourited_type=Property&state=approved';
  <% if @category.present? %>
    url = [url, 'category=<%= @category %>'].join('&');
  <% end %>
  $.ajax({
    type: 'GET',
    url: url,
    dataType: 'script',
  });
<% else %>
  $('#favourited_<%= @property.id %>').html('<%= raw escape_javascript(render "favourited", property: @property, user_favourited_active: false) %>');
<% end %>