konain/config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :pages, only: :show

  resources :projects do
    collection do
      get "fetch_project"
    end
    member do
      get 'fetch_sub_projects'
    end
  end

  ActiveAdmin.routes(self)
  resources :properties

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    member do
      get "assigned_properties"
      get "favourite_properties"
    end
  end

  resources :favourite_properties, only: [:create, :destroy]

  get '/agents', to: "users#agents"

  get '/lawyers', to: "users#lawyers"

  get '/architects', to: 'users#architects'

  post '/send_mail', to: 'emails#send_mail'

  get '/contact_us', to: 'emails#contact'

  post '/send_contact_mail', to: 'emails#send_contact_mail'

  get "/fetch_property_type", to: 'properties#fetch_property_type'

  get "/fetch_property_sub_type", to: 'properties#fetch_property_sub_type'

  get "/fetch_property_features", to: 'properties#fetch_property_features'

  get "/property_types", to: 'properties#property_types'

  get '/about_us', to: 'pages#about_us'

  get '/:permalink', to: "pages#show"

  get '/admin/fetch_types', to:"admin/properties#fetch_types"

  get '/admin/fetch_sub_types', to:"admin/properties#fetch_sub_types"

  get '/admin/fetch_features', to:"admin/properties#fetch_features"

  get '/admin/fetch_sub_projects/(:id)', to: 'admin/properties#fetch_sub_projects'

  root 'properties#home_page'

end

konain/app/views/shared/_attachments_carousel.html.erb
<div class='connected-carousels-transparent'></div>
<div class="connected-carousels">
  <div class="stage">
    <div class="carousel carousel-stage" data-jcarousel="true">
      <ul style="left: 0px; top: 0px;">
        <% attachments.each do |attachment| %>
          <li class="item">
            <%= image_tag(attachment.image.url(:show)) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="navigation">
    <a href="#" class="prev prev-navigation" data-jcarouselcontrol="true">‹</a>
    <a href="#" class="next next-navigation" data-jcarouselcontrol="true">›</a>
    <div class="carousel carousel-navigation" data-jcarousel="true">
      <ul style="left: 0px; top: 0px;">
        <% attachments.each_with_index do |attachment, index| %>
          <%= content_tag :li, class: "#{is_active(index)} carousel-thumb-image" do %>
            <% concat image_tag(attachment.image.url(:thumb), class: "carousel-thumbnail-image") %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

konain/app/views/shared/_banner.html.erb
<header id="banner">
  <div id="banner_container" class="banner-image <%= 'banner-image-default' if check_page_banner?(banner_name, Banner::DEFAULT_BANNER_URL) %>" style="<%= backgroung_image_url(banner_name) %>">
    <div class="banner-back-clr">
      <div class="container">
        <%= content_tag( heading_tag ,  banner_heading, class: "banner-title" ) %>
        <p class="banner-subtitle"></p>
      </div>
    </div>
  </div>
</header>

konain/app/views/shared/_flash_message.html.erb
<div class="container" style="position: relative;">
  <div class="preLoginAlerts <%= alert_holder(params) %> <%= 'HomePageNotification' if @home_page.present? %>">
    <% flash.each do |name, msg| %>
      <div class="<%= flash_class(name) %> fade in">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= content_tag :div, msg.html_safe %>
      </div>
    <% end %>
</div>
</div>

konain/app/views/shared/_footer.html.erb
<section id="footer_widgets">
  <div id="footer_widget_wrapper">
    <div class="container">
      <div class="row-fluid">
        <div class="footerSection">
          <h3>About Konain Marketing</h3>
          <p>
            Token Money:
            Residential Plot = Rs 50,000/-
            Commercial Plot / House = Rs 200,000/-
            Appointment date Seller/Buyer
            1% Commission Full Charge both sides
            No Hidden Charges, No Margin
          </p>
        </div>
        <!-- <div id="text-2" class="span4 widget widget_text">
          <h3 class="widget-title">About Real Expert</h3>
          <div class="textwidget">
            <p>Aquam est tortor, sagittis in fringilla in, pellent esque nec erat.  Aenean semper, neque non faucibus. tortor, sagittis in fringilla in, pellent esque nec eratsemper, neque non.</p>
            <p>Malesuada, dui felis tempor felis, vel varius ante diam ut mais eque non faucibus. tortor, sagittis. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod.</p>
          </div>
        </div>
        <div id="pages-2" class="span2 widget widget_pages offset2">
          <h3 class="widget-title">Quick Links</h3>
          <ul>
            <li class="page_item"><a href="#">Project</a></li>
            <li class="page_item"><a href="#">Contact Us</a></li>
            <li class="page_item"><a href="#">Listing</a></li>
          </ul>
        </div>
        <div id="pages-5" class="span2 widget widget_pages">
          <h3 class="widget-title hidden-phone">&nbsp;</h3>
          <ul>
            <li class="page_item"><a href="#">Property Listing</a></li>
            <li class="page_item"><a href="#">Property Search</a></li>
            <li class="page_item"><a href="#">Special Tabs</a></li>
          </ul>
        </div> -->
      </div>
    </div>
  </div>
</section>
<footer id="footer">
  <div class="container cleafix">
    <p class='pull-left'>Copyright 2012, All Rights Reserved by <a href='#'>Konain Marketing</a></p>
    <div class="pull-right">
      <!-- <ul class="footer-social">
        <li><a href="http://www.facebook.com/" title="Facebook"><i class="fa fa-facebook"></i></a></li>
        <li><a href="http://www.twitter.com/" title="Twitter"><i class="fa fa-twitter"></i></a></li>
      </ul> -->
      <ul class="footerLinks">
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to 'Property Listing', properties_path %>
        </li>
        <li>
          <%= link_to 'Property Types', property_types_path %>
        </li>
        <li>
          <%= link_to 'Agents', agents_path %>
        </li>
        <li>
          <%= link_to "Projects", projects_path %>
        </li>
        <li>
          <%= link_to "Contact Us", contact_us_path %>
        </li>
        <li>
          <%= link_to 'About Us', about_us_path %>
        </li>
      </ul>
    </div>
    <div class="clearfix"></div>
  </div>
</footer>

konain/app/views/shared/_form_image_upload.html.erb
<div class="box-section">
  <h1 class="title-section">Add Images</h1>
  <div class="box-content">
    <div class="target">
      <% if f.object.attachments.exists? %>
        <% f.object.attachments.each do |attachment| %>
          <div class="image-url-div">
            <%= image_tag attachment.image.url(:index), class: "image-preview-size" %>
            <p class="url-txt"><%= attachment.image_file_name %></p>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class='field'>
      <%= f.fields_for :attachments do |attachment| %>
        <% if attachment.object.image.exists? %>
          <p class="url-txt"><%= attachment.object.image_file_name %></p>
        <% else %>
          <p class="url-txt-preview"></p>
          <div class="error-div"></div>
        <% end %>
        <div class="chooseImgFile">
          <%= attachment.file_field :image, class: "pictureInput" %>
          <span class="chooseFileBnt"><i class="fa fa-upload" aria-hidden="true"></i> Choose File</span>
        </div>
        <%= attachment.link_to_remove '', class: "remove-property-image" %>
        <span></span>
      <% end %>
    </div>

    <div class="add-image-btn">
      <%= f.link_to_add :attachments, class: 'btnPrimary' do %>
        <i class="fa fa-plus-circle" aria-hidden="true"></i>  Add an Image
      <% end %>
    </div>
  </div>
</div>

konain/app/views/shared/_header.html.erb
<header id="header" role="banner">
  <div class="header-background">
    <div class="container">
      <div class="row-fluid logo-containe">
        <div class="pull-left logo-sec">
          <%= link_to image_tag("logoKonainMarketing.png"), :root %>
        </div>
        <div class="pull-right">
          <div class="login-btns">
            <ul>
              <li>
                <i class='fa fa-envelope'></i>konainmarketing@gmail.com
              </li>
              <li>
                <i class="fa fa-phone"></i>042-111-786-512
              </li>
              <% if user_signed_in? %>
                <% if current_user.admin? %>
                  <li>
                    <a href="/admin">
                      <i class="fa fa-sign-in fa-rotate-270" aria-hidden="true"></i>ADMIN PANEL
                    </a>
                  </li>
                <% elsif current_user.agent? %>
                  <li>
                    <a href="/admin">
                      <i class="fa fa-sign-in fa-rotate-270" aria-hidden="true"></i>ADMIN PANEL
                    </a>
                  </li>
                  <li>
                    <%= link_to current_user do %>
                      <i class="fa fa-user" aria-hidden="true"></i>
                      <%= "#{current_user.first_name}'s Profile" %>
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to current_user do %>
                      <i class="fa fa-user" aria-hidden="true"></i>
                      <%= "#{current_user.name}'s Profile" %>
                    <% end %>
                  </li>
                <% end %>
                <li class="signoutLink"><%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out" aria-hidden="true"></i>SIGNOUT
              <% end %>
                </li>
              <% else %>
                <li>
                  <a href="/users/sign_up">
                    <i class="fa fa-sign-in fa-rotate-270" aria-hidden="true"></i>SIGNUP
                  </a>
                </li>
                <li>
                  <a href="/users/sign_in">
                    <i class="fa fa-sign-in" aria-hidden="true"></i>LOGIN
                  </a>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="nav-background navbar-static-top">
    <div class="container">
      <div id="social-network" class="hidden-desktop">
        <%= link_to new_property_path, class: 'new-property' do %>
          <i class="fa fa-plus-circle" aria-hidden="true"></i> Add Property
        <% end %>
        <%= render 'shared/social_links' %>
      </div>
      <div class="clearfix navbar">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <div class="nav-collapse collapse">
              <nav id="nav-main" role="navigation">
                <ul id="menu-primary-menu" class="nav">
                  <li class="menu-item dropdown">
                    <li class="menu-item <%= active_tab("properties", "home_page") %>">
                      <%= link_to 'Home', root_path %>
                    </li>
                  <li class='menu-item dropdown <%= active_tab('properties', 'property_types') %>'>
                    <%= link_to 'Property Types', properties_path %>
                    <ul class='dropdown-menu'>
                      <% @all_property_types.each do |type| %>
                        <li class='menu-item'>
                          <%= link_to type, property_types_path(property_type: type) %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                  <li class="menu-item dropdown <%= active_tab("users", "agents") %>">
                    <%= link_to 'Agents', agents_path, class: 'dropdown-toggle' %>
                  </li>
                  <li class="menu-item dropdown <%= active_tab("projects", "index") %>">
                    <%= link_to 'Projects', projects_path %>
                    <ul class="dropdown-menu">
                      <% Project::CITIES.each do |city| %>
                        <li class="menu-item">
                          <%= link_to city, projects_path(city: city) %>
                        </li>
                      <% end %>
                      <li class="menu-item">
                        <%= link_to "Others", projects_path(title: "other") %>
                      </li>
                    </ul>
                  </li>
                  <li class='menu-item <%= active_tab('emails', 'contact') %>'>
                    <%= link_to 'Contact Us', contact_us_path %>
                  </li>
                  <li class='menu-item <%= active_tab('pages', 'about_us') %>'>
                    <%= link_to 'About Us', about_us_path %>
                  </li>
                  <li class="menu-item dropdown" id="property-type-cursor">
                    <%= link_to '#' do %>
                    More <i class="fa fa-sort-desc" aria-hidden="true"></i>
                    <% end %>
                    <ul class="dropdown-menu">
                      <li class="menu-item">
                        <%= link_to "Lawyers", lawyers_path %>
                        <%= link_to 'Architects', architects_path %>
                        <%= link_to 'Property Listing', properties_path %>
                      </li>
                    </ul>
                  </li>
                </ul>
                <div id="social-network" class="visible-desktop">
                  <%# if user_signed_in? && current_user.admin? %>
                    <%#= link_to new_project_path, class: 'new-property' do %>
                      <!-- <i class="fa fa-plus-circle" aria-hidden="true"></i> Add Project -->
                    <%# end %>
                  <%# end %>
                  <%= link_to new_property_path, class: 'new-property' do %>
                    <i class="fa fa-plus-circle" aria-hidden="true"></i> Add Property
                  <% end %>
                  <%= render 'shared/social_links' %>
                </div>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

konain/app/views/shared/_social_links.html.erb
<%= link_to APP_CONFIG[:facebook][:profile_link], class: 'fb', target: '_blank', title: 'Facebook' do %>
  <i class='fa fa-facebook'></i>
<% end %>
<%= link_to APP_CONFIG[:twitter][:profile_link], class: 'tw', target: '_blank', title: 'Twitter' do %>
  <i class='fa fa-twitter'></i>
<% end %>
<%= link_to APP_CONFIG[:googleP][:profile_link], class: 'googleP', target: '_blank', title: 'Google+' do %>
  <i class='fa fa-google-plus'></i>
<% end %>
<%= link_to APP_CONFIG[:linkedin][:profile_link], class: 'linkedin', target: '_blank', title: 'Linkedin' do %>
  <i class='fa fa-linkedin'></i>
<% end %>
<%= link_to "skype:#{APP_CONFIG[:skype][:profile_link]}?chat", class: 'skype', target: '_blank', title: 'Skype' do %>
  <i class='fa fa-skype'></i>
<% end %>